# Generated by Django 5.0 on 2026-05-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_institution_admin_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('class', 'Clase'), ('evaluation', 'Evaluación'), ('task', 'Tarea'), ('meeting', 'Reunión'), ('holiday', 'Festivo/Vacaciones'), ('announcement', 'Anuncio')], default='class', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('course_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.institution')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start'],
                'indexes': [models.Index(fields=['start', 'end'], name='core_schedu_start_f4e99f_idx'), models.Index(fields=['event_type'], name='core_schedu_event_t_f327cf_idx')],
            },
        ),
    ]
