# Generated by Django 5.0.14 on 2026-05-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleevent',
            name='study_material',
            field=models.TextField(blank=True),
        ),
    ]
